import React from "react";
import { Volume2, Lightbulb } from "lucide-react";
import "./QuestionsSection.css";

function QuestionsSection({ codingQuestion, activeQuestionIndex, setActiveQuestionIndex }) {
  const textToSpeech = (text) => {
    if ("speechSynthesis" in window) {
      const speech = new SpeechSynthesisUtterance(text);
      window.speechSynthesis.speak(speech);
    } else {
      alert("Sorry, your browser doesn't support text to speech.");
    }
  };

  return (
    codingQuestion?.length > 0 && (
      <div className="qs-container">
        <h1 className="qs-title">Coding Questions</h1>

        <div className="qs-question-grid">
          {codingQuestion.map((_, index) => (
            <div
              key={index}
              onClick={() => setActiveQuestionIndex(index)}
              className={`qs-question-box ${activeQuestionIndex === index ? "active" : ""}`}
            >
              Question #{index + 1}
            </div>
          ))}
        </div>

        <div className="qs-question-text">
          <h2>{codingQuestion[activeQuestionIndex]?.question}</h2>
          <Volume2
            onClick={() => textToSpeech(codingQuestion[activeQuestionIndex]?.question)}
            className="qs-volume-icon"
          />
        </div>

        <div className="qs-note-box">
          <h2 className="qs-note-title">
            <Lightbulb />
            <strong>Note:</strong>
          </h2>
          <p className="qs-note-text">
            These questions are generated by AI to help you prepare effectively
            for real-world interviews. They are designed based on common
            industry patterns, frequently asked topics, and current job trends.
            While not company-specific, they aim to simulate realistic scenarios
            to improve your problem-solving and communication skills. Use them
            to practice, reflect, and build confidence before your actual
            interviews.
          </p>
        </div>
      </div>
    )
  );
}

export default QuestionsSection;
